import Head from "next/head";
import Hero from "../components/Hero/Hero";
import Instagram from "../components/Instagram/Instagram";
import Slider from "../components/Slider/Slider";
import { SliderData } from "../components/SliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home | Photography </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading="Capture Photography"
        message="I capture moments in nature and keep them alive"
      />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
