import Head from "next/head";
import Hero from "../components/Hero/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero heading="Capture Photography" message='I capture moments in nature and keep them alive' />
    </div>
  );
}
